Algoritmo "exercicio15"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Ler um valor e escrever se é positivo ou
//negativo (considere o valor zero como positivo).
// Autor(a)    : Maria Eduarda Lima da Silva
// Data atual  : 31/08/2026
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("--PROGRAMA VALOR POSITIVO OU NEGATIVO--")
   escreval("")
   escreval("Digite um número: ")
   leia(numero)
   escreval("")
   
   se numero>=0 entao
      escreval("O número é positivo")
   senao
      escreval("O número é negativo")
   fimse

Fimalgoritmo